name: AWS DEPLOY TO STAGING
# turn off deploy to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - dev
  workflow_dispatch:

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{github.ref_name}}
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install

      - run: |
          touch .env
          touch .env2
          touch creds.json
          echo DB_HOST = ${{secrets.DB_HOST}} >> .env
          echo DB_HOST = ${{secrets.DB_HOST}} >> .env2
          echo DB_PW = ${{secrets.DB_PW}} >> .env
          echo DB_USER = ${{secrets.DB_USER}} >> .env
          echo DB_NAME = ${{secrets.DB_NAME}} >> .env
          echo CLIENT_ID = ${{secrets.CLIENT_ID}} >> .env
          echo CLIENT_SECRET = ${{secrets.CLIENT_SECRET}} >> .env
          echo PORT = ${{secrets.PORT}} >> .env
          echo SECRET_PASSWORD = \"${{secrets.SECRET_PASSWORD}}\" >> .env
          echo GOOGLE_APPLICATION_CREDENTIALS = \"./creds.json\" >> .env
          echo EMAIL_USER = ${{secrets.EMAIL_USER}} >> .env
          echo EMAIL_PASS = ${{secrets.EMAIL_PASS}} >> .env

      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "workerscheduling.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/sev2026/t3"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@workerscheduling.eaglesoftwareteam.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/sev2026/t3
            /home/ubuntu/.nvm/versions/node/v24.13.0/bin/node /home/ubuntu/.nvm/versions/node/v24.13.0/bin/npm install
            sudo systemctl stop workerscheduling-t3-backend.service
            sudo cp workerscheduling-t3-backend.service /lib/systemd/system/workerscheduling-t3-backend.service
            sudo systemctl daemon-reload
            sudo systemctl start workerscheduling-t3-backend.service
            touch creds.json
            echo '${{secrets.sa}}' >> creds.json


